version: '3.8'

services:
  mongo:
    image: mongo:7
    platform: linux/amd64
    container_name: taskmanager-mongo-prod
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    platform: linux/amd64
    container_name: taskmanager-backend-prod
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/tasks
      - PORT=4000
    restart: always
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    platform: linux/amd64
    container_name: taskmanager-frontend-prod
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: